# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Coder-bot1/FlyRank-Internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

**Task type: Classification**

I frame my lane as a classification problem. The goal is to predict whether a page is likely to be underperforming in organic search or not.

The model would assign each page to one of two classes:

- `1` = underperforming page
- `0` = not underperforming page

The prediction can be used as decision support to help prioritize which pages should be reviewed first.

In [21]:
print("Task type: Classification")
print("Goal: Predict whether a page is underperforming or not.")

Task type: Classification
Goal: Predict whether a page is underperforming or not.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

The ideal target would be whether a page actually needs improvement and whether an intervention would improve its organic search performance. This outcome is not directly observable in the starter data.

Therefore, I use a measurable proxy based on observed CTR. I classify pages with CTR below the dataset median as underperforming and pages at or above the median as not underperforming.

The target is represented as:

1 = underperforming proxy
0 = not underperforming proxy

This is a directional proxy based on observed performance. A lower CTR does not by itself prove that a page needs a specific change because CTR can also be affected by search intent, position, SERP features, and other factors.

In [22]:
import pandas as pd
from pathlib import Path

data_path = Path("flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv")

df = pd.read_csv(data_path)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 30000
Columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 3. Success metric

*One metric you can defend. What number means 'good'?*

I will use F1 score as the primary success metric.

F1 score balances precision and recall. Precision is important because pages classified as underperforming may be prioritized for review. Recall is important because missing genuinely underperforming pages could cause potentially useful review opportunities to be overlooked.

F1 therefore provides a useful measure for evaluating how well the classifier identifies the underperforming class while balancing false positives and false negatives.

The metric will be used as a measured evaluation metric for decision support, rather than as proof that every predicted page actually needs an intervention.

In [23]:
from sklearn.metrics import f1_score, precision_score, recall_score
print("Primary metric: F1 score")
print("Supporting metrics: Precision and Recall")

Primary metric: F1 score
Supporting metrics: Precision and Recall

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

One row = one page/content item.

Each row represents an individual page identified by content_id. The row contains observed search, traffic, engagement, freshness, and content characteristics for that page.

The proposed classification target is underperforming, which indicates whether the page falls below the dataset median for CTR.

The model would use page-level signals to classify each page and support prioritization for human SEO/content review.

In [24]:
print("Unit of analysis: one row = one page/content item")
print("Dataset shape:", df.shape)
display(df.head(10))

Unit of analysis: one row = one page/content item
Dataset shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,...,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,...,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,...,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,...,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2

In [25]:
# Create a binary target based on observed CTR performance.
# Pages with CTR below the median are labelled as underperforming.

ctr_threshold = df["ctr"].median()

df["underperforming"] = (df["ctr"] < ctr_threshold).astype(int)

print("CTR threshold:", ctr_threshold)
print("\nClass distribution:")
print(df["underperforming"].value_counts())

CTR threshold: 0.07

Class distribution:
underperforming
0    15190
1    14810
Name: count, dtype: int64

In [26]:
print("Class percentages:")

class_percentages = (
    df["underperforming"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(class_percentages)

Class percentages:
underperforming
0    50.63
1    49.37
Name: proportion, dtype: float64

In [27]:
display(
    df[
        [
            "content_id",
            "ctr",
            "avg_position",
            "impressions_90d",
            "clicks_90d",
            "engagement_rate",
            "underperforming"
        ]
    ].head(10)
)

,content_id,ctr,avg_position,impressions_90d,clicks_90d,engagement_rate,underperforming
0,content_304f48230142,0.76,10.6,3803,29,5.88,0
1,content_a1fb4e703a9e,0.05,20.3,15320,7,0.00,1
2,content_9aa793d4d895,0.09,36.5,12581,11,0.00,0
3,content_331d6c4de07b,0.49,6.2,11751,58,1.28,0
4,content_d99b7a2d90ca,0.13,44.0,19140,24,0.00,0
5,content_d4084a4bc775,0.03,8.5,3970,1,0.00,1
6,content_9a34b442b552,0.00,7.0,20,0,0.00,1
7,content_a63219c6e95a,0.06,21.2,1724,1,3.57,1
8,content_5e6c160719bc,0.09,46.0,32574,29,5.88,0
9,content_c27558df2b0c,0.16,4.9,1240,2,0.00,0

### Proposed target column

The proposed target column is `underperforming`.

A value of `1` indicates that the page has a CTR below the dataset median, while `0` indicates that the page has a CTR at or above the median.

This creates the two classes required for the classification framing. The target is a proxy derived from observed data, so it should be interpreted as directional rather than as a definitive judgement about page quality.

In [28]:
lane_df = df[
    [
        "content_id",
        "search_volume",
        "competition",
        "content_type",
        "main_intent",
        "word_count",
        "impressions_90d",
        "clicks_90d",
        "pageviews_90d",
        "sessions_90d",
        "engagement_rate",
        "scroll_rate",
        "ai_traffic_pct",
        "content_age_days",
        "days_since_last_update",
        "trend_direction",
        "trend_pct",
        "underperforming"
    ]
].copy()

display(lane_df.head(10))

,content_id,search_volume,competition,content_type,main_intent,word_count,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,engagement_rate,scroll_rate,ai_traffic_pct,content_age_days,days_since_last_update,trend_direction,trend_pct,underperforming
0,content_304f48230142,10.0,0.67,keyword article,transactional,3221.0,3803,29,22,17,5.88,4.55,0.0,187,20,down,-41.4,0
1,content_a1fb4e703a9e,90.0,0.01,keyword article,informational,2481.0,15320,7,10,9,0.00,10.00,0.0,445,25,down,-57.7,1
2,content_9aa793d4d895,0.0,0.00,keyword article,informational,3515.0,12581,11,14,11,0.00,28.57,0.0,141,20,down,-60.9,0
3,content_331d6c4de07b,10.0,0.00,keyword article,commercial,NaN,11751,58,87,78,1.28,3.45,0.0,463,22,stable,-13.8,0
4,content_d99b7a2d90ca,0.0,0.00,keyword article,informational,2803.0,19140,24,177,145,0.00,24.29,0.0,263,14,down,-34.7,0
5,content_d4084a4bc775,720.0,1.00,keyword article,transactional,3080.0,3970,1,4,5,0.00,25.00,0.0,147,20,down,-38.9,1
6,content_9a34b442b552,0.0,0.00,keyword article,informational,3059.0,20,0,1,1,0.00,0.00,0.0,90,20,down,-92.3,1
7,content_a63219c6e95a,590.0,0.44,keyword article,commercial,NaN,1724,1,28,28,3.57,7.14,0.0,445,22,stable,0.6,1
8,content_5e6c160719bc,0.0,0.00,keyword article,informational,3807.0,32574,29,128,68,5.88,6.25,0.0,90,20,down,-58.8,0
9,content_c27558df2b0c,0.0,0.00,keyword article,informational,NaN,1240,2,4,3,0.00,0.00,0.0,257,104,down,-29.2,0

In [29]:
print("Rows:", lane_df.shape[0])
print("Columns:", lane_df.shape[1])

print("\nMissing values:")
display(lane_df.isnull().sum())

Rows: 30000
Columns: 18

Missing values:

content_id                   0
search_volume             2468
competition               2468
content_type                 0
main_intent               2374
word_count                7699
impressions_90d              0
clicks_90d                   0
pageviews_90d                0
sessions_90d                 0
engagement_rate              0
scroll_rate                125
ai_traffic_pct               0
content_age_days             0
days_since_last_update       0
trend_direction              0
trend_pct                 3388
underperforming              0
dtype: int64

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A fixed rule could classify pages using CTR alone, such as marking every page below the median CTR as underperforming. This approach is simple and transparent, but it only considers one signal.

ML can combine multiple observed page-level and search-performance signals such as search volume, competition, content type, word count, impressions, clicks, average position, engagement, freshness, and traffic trends.

A classifier could therefore learn patterns across several variables instead of relying on a single manually selected threshold.

The classification output would support a practical content and SEO action: pages predicted as underperforming could be prioritized for human review.

The model would provide decision support rather than automatically deciding what should be changed. Its predictions would be treated as measured and directional signals that help determine which pages deserve further investigation.

In [30]:
print("Decision supported:")
print("Prioritize pages predicted as underperforming for human SEO/content review.")

print("\nWhy use ML:")
print("ML can combine multiple observed signals instead of relying on one fixed rule.")

print("\nImportant limitation:")
print("The classification is decision support and does not prove that a page requires a specific change.")

Decision supported:
Prioritize pages predicted as underperforming for human SEO/content review.

Why use ML:
ML can combine multiple observed signals instead of relying on one fixed rule.

Important limitation:
The classification is decision support and does not prove that a page requires a specific change.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.